### ISSUE TITLE
Specific train / test split used for the published trained model

### ISSUE THREAD

**Issue by aplzr** [dslaborg/sumo#11]
First off, many thanks for publishing the model and code together with your paper, it is much appreciated.

I'm currently trying to reproduce the results published in https://www.nature.com/articles/s41598-022-11210-y. For this I would need the specific split of the whole MASS SS2 dataset into training and test that was used for training the published model. In your paper you list various statistical properties of the two sets, and the code in [scripts/create_data_splits.py](https://github.com/dslaborg/sumo/blob/main/scripts/create_data_splits.py) shows how to create random splits that fulfil these criteria, but as far as I can see the specific split used for training the published model is not documented. Could you publish this information (or point me to its location if it's already published), i.e. which specific segments of MASS SS2 were used for training and which segments were used for testing?

Also pinging @n-grieger directly as they're the one having answered the previous issues but don't seem to be a member of this repo.

**Comment by n-grieger** [comment]
Hi @aplzr, unfortunately, I'm not entirely sure about the data split either, since it wasn't written down anywhere. However, I did find files on our server with the data split shown below. Please take this information with a grain of salt, as I haven't tested if this is indeed the split used in the paper.

### Data split for cross validation:

| fold | subjects |
| --- | --- |
| fold_0 | ['01-04-0019', '01-03-0009', '01-04-0002', '01-04-0012', '01-01-0031', '01-03-0032', '01-03-0047', '01-01-0042', '01-04-0033', '01-02-0001', '01-04-0020', '01-03-0010', '01-03-0013', '01-01-0051', '01-03-0045', '01-04-0021', '01-05-0022', '01-02-0015', '01-01-0006', '01-05-0010', '01-05-0015', '01-01-0014', '01-01-0019', '01-05-0003']|
| fold_1 | ['01-03-0050', '01-03-0034', '01-05-0016', '01-03-0021', '01-03-0015', '01-03-0002', '01-03-0024', '01-03-0025', '01-01-0005', '01-03-0008', '01-02-0003', '01-01-0052', '01-03-0018', '01-03-0036', '01-04-0031', '01-03-0046', '01-01-0047', '01-01-0037', '01-03-0041', '01-05-0004', '01-05-0013', '01-01-0010', '01-01-0001', '01-05-0001'] |
| fold_2 | ['01-03-0016', '01-04-0026', '01-02-0017', '01-03-0063', '01-01-0024', '01-03-0044', '01-03-0061', '01-03-0037', '01-04-0028', '01-04-0023', '01-04-0011', '01-04-0040', '01-03-0039', '01-05-0025', '01-04-0038', '01-01-0053', '01-01-0025', '01-03-0022', '01-04-0037', '01-01-0013', '01-01-0012', '01-05-0006', '01-05-0017', '01-05-0014'] |
| fold_3 | ['01-03-0006', '01-04-0022', '01-03-0056', '01-04-0018', '01-02-0019', '01-03-0019', '01-05-0019', '01-01-0026', '01-03-0042', '01-01-0030', '01-01-0040', '01-02-0012', '01-04-0017', '01-04-0003', '01-04-0034', '01-01-0036', '01-04-0009', '01-04-0030', '01-03-0029', '01-01-0008', '01-01-0011', '01-05-0011', '01-01-0021', '01-05-0009'] |
| fold_4 | ['01-01-0035', '01-04-0025', '01-03-0007', '01-01-0041', '01-01-0038', '01-03-0053', '01-03-0035', '01-04-0014', '01-04-0036', '01-03-0052', '01-02-0014', '01-04-0006', '01-03-0001', '01-03-0017', '01-02-0011', '01-01-0027', '01-03-0020', '01-02-0005', '01-03-0058', '01-01-0017', '01-05-0008', '01-05-0007', '01-01-0022', '01-01-0018'] |
| fold_5 | ['01-03-0011', '01-01-0003', '01-03-0038', '01-01-0032', '01-03-0048', '01-03-0028', '01-02-0002', '01-02-0013', '01-04-0005', '01-05-0023', '01-03-0005', '01-03-0057', '01-04-0035', '01-01-0050', '01-01-0033', '01-03-0030', '01-01-0002', '01-03-0054', '01-02-0004', '01-05-0012', '01-01-0016', '01-01-0020', '01-01-0007', '01-05-0005'] |
| test phase_0 | ['01-05-0024', '01-05-0020', '01-04-0013', '01-03-0033', '01-03-0023', '01-04-0008', '01-04-0029', '01-05-0002', '01-04-0015', '01-04-0007', '01-03-0003', '01-02-0006', '01-05-0018', '01-03-0059', '01-03-0040', '01-03-0004', '01-04-0016', '01-02-0010']|
| test phase_1 | ['01-03-0060', '01-03-0026', '01-01-0023', '01-03-0062', '01-01-0046', '01-01-0048', '01-03-0051', '01-03-0012', '01-01-0044', '01-03-0064', '01-01-0043', '01-01-0029', '01-03-0027', '01-01-0028', '01-03-0031', '01-03-0014', '01-01-0049', '01-01-0004']|

### Data split for hold-out validation:

| dataset | subjects |
| --- | --- |
| train | ['01-01-0040', '01-04-0005', '01-04-0018', '01-01-0011', '01-01-0016', '01-03-0016', '01-03-0036', '01-03-0013', '01-03-0018', '01-02-0005', '01-05-0023', '01-01-0033', '01-03-0037', '01-05-0017', '01-05-0007', '01-01-0050', '01-05-0006', '01-04-0017', '01-01-0024', '01-01-0041', '01-03-0041', '01-03-0035', '01-04-0030', '01-04-0026', '01-04-0036', '01-04-0025', '01-01-0012', '01-02-0004', '01-05-0014', '01-01-0042', '01-03-0011', '01-01-0026', '01-01-0010', '01-01-0001', '01-01-0017', '01-03-0047', '01-03-0015', '01-04-0019', '01-03-0010', '01-04-0033', '01-04-0037', '01-01-0019', '01-03-0039', '01-04-0020', '01-01-0027', '01-03-0038', '01-03-0034', '01-03-0050', '01-01-0006', '01-01-0014', '01-01-0025', '01-03-0019', '01-03-0044', '01-05-0011', '01-05-0005', '01-03-0045', '01-02-0014', '01-03-0032', '01-01-0031', '01-04-0011', '01-04-0014', '01-03-0063', '01-05-0003', '01-01-0035', '01-03-0007', '01-04-0038', '01-03-0029', '01-03-0021', '01-03-0061', '01-01-0002', '01-01-0020', '01-03-0030', '01-04-0023', '01-04-0031', '01-02-0002', '01-01-0032', '01-05-0016', '01-04-0028', '01-02-0013', '01-01-0022', '01-05-0009', '01-03-0053', '01-02-0015', '01-03-0024', '01-04-0012', '01-01-0003', '01-03-0008', '01-04-0006', '01-04-0034', '01-05-0013', '01-03-0028', '01-03-0058', '01-04-0009', '01-01-0021', '01-03-0005', '01-04-0035', '01-03-0046', '01-03-0057', '01-01-0037', '01-03-0006', '01-03-0022', '01-05-0019', '01-01-0038', '01-01-0053', '01-03-0009', '01-02-0019', '01-03-0048', '01-01-0052', '01-03-0002', '01-02-0011', '01-02-0017', '01-01-0051', '01-05-0010', '01-04-0021', '01-03-0017', '01-02-0012', '01-03-0054', '01-04-0022', '01-02-0001', '01-04-0040', '01-04-0003', '01-01-0018', '01-03-0052', '01-03-0056', '01-01-0007', '01-01-0036', '01-03-0025', '01-05-0025', '01-05-0008'] |
| val | ['01-01-0005', '01-01-0008', '01-01-0030', '01-05-0012', '01-05-0022', '01-03-0020', '01-04-0002', '01-05-0001', '01-01-0047', '01-02-0003', '01-03-0001', '01-03-0042', '01-01-0013', '01-05-0004', '01-05-0015'] |
| test phase_0 | ['01-05-0024', '01-05-0020', '01-04-0013', '01-03-0033', '01-03-0023', '01-04-0008', '01-04-0029', '01-05-0002', '01-04-0015', '01-04-0007', '01-03-0003', '01-02-0006', '01-05-0018', '01-03-0059', '01-03-0040', '01-03-0004', '01-04-0016', '01-02-0010'] |
| test phase_1 | ['01-03-0060', '01-03-0026', '01-01-0023', '01-03-0062', '01-01-0046', '01-01-0048', '01-03-0051', '01-03-0012', '01-01-0044', '01-03-0064', '01-01-0043', '01-01-0029', '01-03-0027', '01-01-0028', '01-03-0031', '01-03-0014', '01-01-0049', '01-01-0004'] |

Hope this helps :slightly_smiling_face: 

And please let us know if you are able to reproduce the numbers shown in the paper with this split. I will then incorporate this information into the repo :+1:

**Comment by aplzr** [comment]
Hi @n-grieger, thanks for the quick response and the detective work. Let's see how far I can get with his 🙂

**Comment by aplzr** [comment]
Hi @n-grieger, it took me a moment until I had the time to pursue this further, but now I have some results. I tested the published model on the test set from your comment above.

### Published results from your paper
![sumo_published_results](https://github.com/user-attachments/assets/15c15b80-4277-46f3-bba9-826d708f0cf0)

### My reproduction of these results using the test set from your split
![reproduction_of_sumo_published_results](https://github.com/user-attachments/assets/5b12c876-9a16-47fc-bf0f-2a4d6dc2dc3d)

Comparing the orange line in the left panel of your results with the blue line in my plot and the orange line in the right panel of your results with the orange line in mine, I'd say the shapes are identical. Initially I thought that my lines were very slightly shifted towards lower values compared to yours, but on closer inspection that doesn't actually seem to be the case. It's impossible to say for certain whether they match by only comparing visually, but I'd say we're reasonably close in any case.

This still doesn't necessarily mean that the split from your comment above was the one used to train and test the published model, but I'd say there's a pretty high likelihood that it was 🙂 

### Code for reproduction
[reproduce_sumo_results.zip](https://github.com/user-attachments/files/17845545/reproduce_sumo_results.zip)

**Comment by n-grieger** [comment]
Hi @aplzr, great work! Thank you for testing the split. Based on your results, it looks like this was indeed the split used in the study. And even if it is not, it looks like the split at least produces results very similar to those reported in the paper. I will include information about the split in the README.md.

**Comment by aplzr** [comment]
My pleasure, and thanks again for your assistance.
